In [ ]:
from pandas import read_csv, read_excel
from pandas import isna, DataFrame
from typing import Dict, List

In [82]:
ILLEGAL_CHARS_FOR_EXCEL_FILE = [
        '\x00',
        '\x01',
        '\x02',
        '\x03',
        '\x04',
        '\x05',
        '\x06',
        '\x07',
        '\x08',
        '\x0b',
        '\x0c',
        '\x0e',
        '\x0f',
        '\x10',
        '\x11',
        '\x12',
        '\x13',
        '\x14',
        '\x15',
        '\x16',
        '\x17',
        '\x18',
        '\x19',
        '\x1a',
        '\x1b',
        '\x1c',
        '\x1d',
        '\x1e',
        '\x1f'
]

def removeIllegalChars(__st : str) -> str :
    for illegal_char in ILLEGAL_CHARS_FOR_EXCEL_FILE :
        __st = __st.replace(illegal_char, "")
    return __st

In [3]:
df = read_csv("Airline-Sentiment-2-w-AA.csv", encoding="latin-1")

In [4]:
df.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,airline_sentiment,airline_sentiment:confidence,negativereason,negativereason:confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,681448150,False,finalized,3,2/25/15 5:24,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2/24/15 11:35,5.703060e+17,NaN,Eastern Time (US & Canada)
1,681448153,False,finalized,3,2/25/15 1:53,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2/24/15 11:15,5.703010e+17,NaN,Pacific Time (US & Canada)
2,681448156,False,finalized,3,2/25/15 10:01,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2/24/15 11:15,5.703010e+17,Lets Play,Central Time (US & Canada)
3,681448158,False,finalized,3,2/25/15 3:05,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2/24/15 11:15,5.703010e+17,NaN,Pacific Time (US & Canada)
4,681448159,False,finalized,3,2/25/15 5:50,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2/24/15 11:14,5.703010e+17,NaN,Pacific Time (US & Canada)

In [8]:
df.tail()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,airline_sentiment,airline_sentiment:confidence,negativereason,negativereason:confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
14635,681679794,False,finalized,3,2/25/15 19:46,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2/22/15 12:01,5.695880e+17,NaN,NaN
14636,681679795,False,finalized,3,2/25/15 19:14,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2/22/15 11:59,5.695870e+17,Texas,NaN
14637,681679796,False,finalized,3,2/25/15 19:04,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2/22/15 11:59,5.695870e+17,"Nigeria,lagos",NaN
14638,681679797,False,finalized,3,2/25/15 18:59,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2/22/15 11:59,5.695870e+17,New Jersey,Eastern Time (US & Canada)
14639,681679798,False,finalized,3,2/25/15 19:06,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2/22/15 11:58,5.695870e+17,"dallas, TX",NaN

In [6]:
df.iloc[6]["text"]

'@VirginAmerica yes, nearly every time I fly VX this \x89ÛÏear worm\x89Û\x9d won\x89Ûªt go away :)'

In [22]:
lst_of_cleaned_data : List[Dict[str , str | int]] = []

In [29]:
def getSentimentNumber(__sentiment : str | None) -> int :

    if __sentiment is None : raise Exception("Don't you dare to paas a null/none value to me")
    
    __sentiment = __sentiment.lower().strip()

    if __sentiment == "positive" : return 1

    elif __sentiment == "neutral" : return 0

    elif __sentiment == "negative" : return 2

    raise Exception("Found invalid sentiment value '" + __sentiment + "'")

In [24]:


for i in range(df.__len__()) :
    cur_row = df.iloc[i]

    comment_text = cur_row["text"].strip()

    if(comment_text.__len__()) == 0 :continue

    lst_of_cleaned_data.append({
        "text" : comment_text,
        "sentiment" : getSentimentNumber(cur_row["airline_sentiment"])
    })

In [25]:
DataFrame(lst_of_cleaned_data).to_excel("cb-data-v1.xlsx", index=False)

In [30]:
# 1 Negative
# 3 Neutral
# 5 Positive

df = read_csv("Apple-Twitter-Sentiment-DFE.csv", encoding="latin-1")

In [31]:
df.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,sentiment,sentiment:confidence,date,id,query,sentiment_gold,text
0,623495513,True,golden,10,NaN,3,0.6264,Mon Dec 01 19:30:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\nnot_relevant,#AAPL:The 10 best Steve Jobs emails ever...htt...
1,623495514,True,golden,12,NaN,3,0.8129,Mon Dec 01 19:43:51 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\n1,RT @JPDesloges: Why AAPL Stock Had a Mini-Flas...
2,623495515,True,golden,10,NaN,3,1.0000,Mon Dec 01 19:50:28 +0000 2014,5.400000e+17,#AAPL OR @Apple,3,My cat only chews @apple cords. Such an #Apple...
3,623495516,True,golden,17,NaN,3,0.5848,Mon Dec 01 20:26:34 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\n1,I agree with @jimcramer that the #IndividualIn...
4,623495517,False,finalized,3,12/12/14 12:14,3,0.6474,Mon Dec 01 20:29:33 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Nobody expects the Spanish Inquisition #AAPL

In [34]:
lst_of_cleaned_data.clear()

sentiment_number_dt = {
    1 : "negative",
    3 : "neutral",
    5 : "positive"
}

for i in range(df.__len__()) :
    cur_row = df.iloc[i]

    comment_text = cur_row["text"].strip()

    if comment_text.__len__() == 0 or cur_row["sentiment"] == "not_relevant" :continue

    lst_of_cleaned_data.append({
        "text" : comment_text,
        "sentiment" : getSentimentNumber(sentiment_number_dt.get(int(cur_row["sentiment"])))
    })

In [35]:
len(lst_of_cleaned_data)

3804

In [38]:
DataFrame(lst_of_cleaned_data).to_excel("cb-data-v2.xlsx", index=False)

In [72]:
df = read_csv("IMDB-Dataset.csv", encoding="utf-8")

In [73]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [83]:
lst_of_cleaned_data.clear()

# Source - https://stackoverflow.com/a/42365230
# Posted by user4896331
# Retrieved 2026-03-14, License - CC BY-SA 3.0

# df = df.apply(lambda x: x.encode('unicode_escape').decode('utf-8') if isinstance(x, str) else x)

for i in range(df.__len__()) :
    cur_row = df.iloc[i]

    comment_text = str(cur_row["review"]).replace("<br/>", "\n").replace("<br />", "\n").replace("<br>", "\n").replace("\t", " ").strip()
    comment_text = removeIllegalChars(comment_text).strip()
    if comment_text.__len__() == 0 :continue

    lst_of_cleaned_data.append({
        "text" : comment_text,
        "sentiment" : getSentimentNumber(cur_row["sentiment"])
    })

In [84]:
DataFrame(lst_of_cleaned_data).to_excel("cb-data-v3.xlsx", index=False)