In [1]:
from pandas import DataFrame, read_csv, isna

In [3]:
!wget -P data/full_dataset/ https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv
!wget -P data/full_dataset/ https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv
!wget -P data/full_dataset/ https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv

--2026-10-03 01:56:38--  https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 34.144.170.27, 34.3.1.27, 34.144.171.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.144.170.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14174600 (14M) [application/octet-stream]
Saving to: ‘data/full_dataset/goemotions_1.csv’

goemotions_1.csv    100%[===================>]  13.52M  89.3MB/s    in 0.2s

2026-10-03 01:56:38 (89.3 MB/s) - ‘data/full_dataset/goemotions_1.csv’ saved [14174600/14174600]

--2026-10-03 01:56:38--  https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 34.144.170.27, 34.3.1.27, 34.144.171.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.144.170.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14173154 (14M) [application/octet-stream]
Saving to: ‘data/full_dataset/goemotions_2.csv’

goemotions_2.csv    100%[===================>]  13.52M  --.-KB/s    in 0.1s

2026-10-03 01:56:39 (105 MB/s) - ‘data/full_dataset/goemotions_2.csv’ saved [14173154/14173154]

--2026-10-03 01:56:39--  https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 34.144.170.27, 34.3.1.27, 34.144.171.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.144.170.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14395164 (14M) [application/octet-stream]
Saving to: ‘data/full_dataset/goemotions_3.csv’

goemotions_3.csv    100%[===================>]  13.73M  89.3MB/s    in 0.2s

2026-10-03 01:56:39 (89.3 MB/s) - ‘data/full_dataset/goemotions_3.csv’ saved [14395164/14395164]

In [4]:
!ls -a

.  ..  .config	data  sample_data

In [5]:
df1 = read_csv("data/full_dataset/goemotions_1.csv")
df2 = read_csv("data/full_dataset/goemotions_2.csv")
df3 = read_csv("data/full_dataset/goemotions_3.csv")

In [6]:
df1.head()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,eew5j0j,Brdd9,nrl,t3_ajis4z,t1_eew18eq,1.548381e+09,1,False,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,eemcysk,TheGreen888,unpopularopinion,t3_ai4q37,t3_ai4q37,1.548084e+09,37,True,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",ed2mah1,Labalool,confessions,t3_abru74,t1_ed2m7g7,1.546428e+09,37,False,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,eeibobj,MrsRobertshaw,facepalm,t3_ahulml,t3_ahulml,1.547965e+09,18,False,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",eda6yn6,American_Fascist713,starwarsspeculation,t3_ackt2f,t1_eda65q2,1.546669e+09,2,False,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
df2.head()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,We can hope,ee3o3ko,darkenseyreth,EdmontonOilers,t3_ag4r9j,t1_ee3mhad,1.547529e+09,62,False,0,...,0,0,1,0,0,0,0,0,0,0
1,Shhh don't give them the idea!,eebl3z7,BoinkBoinkEtAliae,MurderedByWords,t3_ah3o76,t1_eeb68lo,1.547777e+09,76,False,0,...,0,0,0,0,0,0,0,0,0,0
2,"Thank you so much, kind stranger. I really nee...",ed4fe9l,savageleaf,raisedbynarcissists,t3_abwh00,t1_ed4etbj,1.546482e+09,24,False,0,...,0,0,0,0,0,0,0,0,0,0
3,Ion know but it would be better for you to jus...,efavtdu,CADDiLLXC,darknet,t3_al4njw,t3_al4njw,1.548800e+09,62,False,0,...,0,0,0,0,0,0,0,0,0,1
4,I'm honestly surprised. We should have fallen ...,ee2imz2,CorporalThornberry,CollegeBasketball,t3_afxt6t,t1_ee22nyr,1.547497e+09,55,False,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df3.head()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,Worst ending ever! I won't spoil it but this o...,eee021b,tribaltrak,movies,t3_agxbsx,t3_agxbsx,1.547847e+09,42,False,0,...,0,0,0,0,0,0,0,0,0,0
1,Happy cake day u/sneakpeekbot!,ed00f1z,InfernicFuse,danganronpa,t3_abajdo,t1_eczoocj,1.546328e+09,24,False,0,...,0,0,0,0,0,0,0,0,0,0
2,Was he rejected because of his methodology or ...,ee1h5v1,OssToYouGoodSir,medicine,t3_aflo7s,t1_ee0v0vv,1.547464e+09,77,False,0,...,0,0,0,0,0,0,0,0,0,0
3,"thanks, I agree",eemi935,PMOFreeForever,NoFap,t3_ai7h09,t1_eelu54r,1.548088e+09,46,False,0,...,0,0,0,0,0,0,0,0,0,0
4,Why would you doubt it dumbass?,eduun99,ugliestman1,Tinder,t3_aejwne,t1_edumeal,1.547255e+09,36,False,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
print(len(df1))
print(len(df2))
print(len(df3))

70000
70000
71225

In [10]:
df1.tail()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
69995,"It's about fucking time, hope this is real.",eeuoyeh,DudeImMacGyver,worldnews,t3_ajcbgq,t3_ajcbgq,1.548346e+09,19,False,0,...,0,0,0,0,0,0,0,0,0,0
69996,This is great! Can anyone make a request with ...,eer0igi,Dirkus777,gay,t3_aiqhx1,t3_aiqhx1,1.548223e+09,55,False,1,...,0,0,0,0,0,0,0,0,0,0
69997,I’m sorry. Can you please explain what are the...,eebxspf,menjav,DebateAnAtheist,t3_ah451r,t1_eeblb39,1.547787e+09,5,False,0,...,0,0,0,0,0,0,0,0,0,0
69998,No but it should be,edjf4v2,heputmystuffinjello,DunderMifflin,t3_adpkeq,t1_edjasoe,1.546922e+09,51,False,0,...,0,0,0,0,0,0,0,0,0,1
69999,This is so cruel. I literally feel physically ...,ee3dzap,ColeKXL9,antinatalism,t3_ag2259,t3_ag2259,1.547520e+09,4,False,0,...,0,0,0,0,0,0,0,1,0,0

In [11]:
df2.tail()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
69995,I would cheer hard for a Cyborg win in that to...,eczbpfi,topforthis,MMA,t3_ab689g,t1_ecxtwqy,1.546301e+09,49,False,0,...,1,0,0,0,0,0,0,0,0,0
69996,"That's scalie, loli, and gmilf at the same time",eerd9bz,Antimoney,furry_irl,t3_aiv4iy,t1_eer7ue2,1.548243e+09,40,False,0,...,0,0,0,0,0,0,0,0,0,1
69997,I have the worst memory ever. Idk if it's from...,efev9va,maddiokii,depression,t3_al9tkd,t3_al9tkd,1.548905e+09,51,False,0,...,0,0,0,0,0,0,0,0,0,0
69998,So angry. PMS?,ee4sic2,PhillyGreg,Connecticut,t3_ag1kvx,t1_ee3mkp1,1.547573e+09,49,False,0,...,0,0,0,0,0,0,0,0,0,0
69999,"I mean, you can definitely beat someone up pas...",eeij0ow,tb_Crunch,unpopularopinion,t3_ahvr4j,t1_eeiiwk2,1.547974e+09,51,False,1,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df3.tail()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
71220,Everyone likes [NAME].,ee6pagw,Senshado,heroesofthestorm,t3_agjf24,t3_agjf24,1.547634e+09,16,False,0,...,1,0,0,0,0,0,0,0,0,0
71221,Well when you’ve imported about a gazillion of...,ef28nod,5inchloser,nottheonion,t3_ak26t3,t3_ak26t3,1.548553e+09,15,False,0,...,0,0,0,0,0,0,0,0,0,0
71222,That looks amazing,ee8hse1,springt1me,shittyfoodporn,t3_agrnqb,t3_agrnqb,1.547684e+09,70,False,1,...,0,0,0,0,0,0,0,0,0,0
71223,The FDA has plenty to criticize. But like here...,edrhoxh,enamedata,medicine,t3_aejqzd,t1_edrgdtx,1.547169e+09,4,False,0,...,0,0,0,0,0,0,0,0,0,0
71224,Desktop link: ^^/r/HelperBot_ ^^Downvote ^^to ...,edze9g4,HelperBot_,MorbidReality,t3_afhw30,t1_edze91s,1.547397e+09,61,True,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df1.columns

Index(['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id',
       'created_utc', 'rater_id', 'example_very_unclear', 'admiration',
       'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
       'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy',
       'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
       'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [17]:
columns_with_emotions = ['admiration',
       'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
       'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy',
       'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
       'remorse', 'sadness', 'surprise', 'neutral']

len(columns_with_emotions)

28

In [21]:
emotion_values_set = set()

for i in (df1, df2, df3) :
    for column in columns_with_emotions :
        for j in range(len(i)) :
            emotion_values_set.add(i.iloc[j][column])

emotion_values_set

{np.int64(0), np.int64(1)}

In [ ]:
json_input = []

for i in (df1, df2, df3) :
    for j in range(len(i)) :
        dt = {
            "text" : i.iloc[j]["text"],
            "emotions" : []
        }
        for column in columns_with_emotions :
            if int(i.iloc[j][column]) == 1 : dt["emotions"].append(column)
        json_input.append(dt)

In [23]:
json_input[0]

{'text': 'That game hurt.', 'emotions': ['sadness']}

In [ ]:
from json5 import dump

with open("sample_data/goemotions-eng.json", "w") as file:
    dump(json_input, file, indent=4, ensure_ascii=False, trailing_commas=False, allow_nan=False, quote_keys=True)

In [28]:
!ls

data  refined_set.json	sample_data